/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class ViewLogin extends javax.swing.JFrame {
    Connection conn = null;
    Statement st = null;
    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/dbbacanovel", "root", "");
            st = conn.createStatement();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal terkoneksi Karena " + ex);
         }
    }

    
    private void CekLogin(){
        try{
            // Memeriksa apakah kolom email atau password kosong
            if(txt_input_email.getText().equals("") || txt_input_password.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                txt_input_email.requestFocus();
                HapusLayar();
            }else{
                st = conn.createStatement();
                // Membuat query SQL untuk mencari data login yang sesuai dengan email dan password yang dimasukkan
                String sql = ("SELECT * FROM tblogin WHERE email ='"+txt_input_email.getText()+"' AND password ='"+String.valueOf(txt_input_password.getText())+"'");
                ResultSet rs = st.executeQuery(sql);
                
                if(rs.next()){
                    this.dispose(); 
                    new ViewNovel().setVisible(true);
                }else{
                    // Jika data login tidak ditemukan, tampilkan pesan kesalahan
                    JOptionPane.showMessageDialog(rootPane, "UserName dan Password Salah\nAtau Akun Belum Terdaftar", "Pesan",JOptionPane.ERROR_MESSAGE);
                    HapusLayar(); // Memanggil fungsi HapusLayar()
                }
            }
        }catch(Exception e){
            e.printStackTrace(); // Menampilkan jejak eksepsi jika terjadi kesalahan
        }
    }
    
    private void HapusLayar(){
        txt_input_email.setText("");
        txt_input_password.setText("");
        txt_input_email.setEnabled(true);
        txt_input_password.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input_email = new javax.swing.JTextField();
        txt_input_password = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_daftardisini = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UILogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input_email.setBackground(new java.awt.Color(234, 234, 234));
        txt_input_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_input_email.setBorder(null);
        txt_input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 340, 50));

        txt_input_password.setBackground(new java.awt.Color(229, 229, 229));
        txt_input_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_input_password.setBorder(null);
        txt_input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 340, 50));

        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 260, 70));

        btn_daftardisini.setBorder(null);
        btn_daftardisini.setBorderPainted(false);
        btn_daftardisini.setContentAreaFilled(false);
        btn_daftardisini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftardisiniActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftardisini, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        UILogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UiAsset/HalamanLogin.png"))); // NOI18N
        getContentPane().add(UILogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_emailActionPerformed

    private void txt_input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_passwordActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        CekLogin();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_daftardisiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftardisiniActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewRegister().setVisible(true);
    }//GEN-LAST:event_btn_daftardisiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UILogin;
    private javax.swing.JButton btn_daftardisini;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_input_email;
    private javax.swing.JTextField txt_input_password;
    // End of variables declaration//GEN-END:variables
}
