/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author user
 */
public class ViewRegister extends javax.swing.JFrame {
    Connection conn = null;
    Statement st = null;

    /**
     * Creates new form ViewRegister
     */
    public ViewRegister() {
        initComponents();
    }
    
    private void hapuslayar(){
        txt_email_register.setText("");
        txt_nama_register.setText("");
        txt_password_register.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama_register = new javax.swing.JTextField();
        txt_email_register = new javax.swing.JTextField();
        txt_password_register = new javax.swing.JTextField();
        btn_daftar = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        UIRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        txt_nama_register.setBackground(new java.awt.Color(234, 234, 234));
        txt_nama_register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nama_register.setBorder(null);
        txt_nama_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_registerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 340, 50));

        txt_email_register.setBackground(new java.awt.Color(229, 229, 229));
        txt_email_register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_email_register.setBorder(null);
        txt_email_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_registerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 340, 50));

        txt_password_register.setBackground(new java.awt.Color(229, 229, 229));
        txt_password_register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password_register.setBorder(null);
        txt_password_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_registerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 340, 50));

        btn_daftar.setBorder(null);
        btn_daftar.setBorderPainted(false);
        btn_daftar.setContentAreaFilled(false);
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 270, 60));

        btn_cancel.setBorder(null);
        btn_cancel.setBorderPainted(false);
        btn_cancel.setContentAreaFilled(false);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 710, 190, 40));

        UIRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UiAsset/HalamanRegister.png"))); // NOI18N
        getContentPane().add(UIRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nama_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_registerActionPerformed

    private void txt_email_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_registerActionPerformed

    private void txt_password_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_registerActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        try{
            if(txt_email_register.getText().equals("") || txt_nama_register.getText().equals("") || txt_password_register.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                hapuslayar();

            }else{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost/dbbacanovel","root","");
                st=conn.createStatement();
                String simpan = "INSERT INTO tblogin VALUES('"+txt_email_register.getText()+"','"+String.valueOf(txt_nama_register.getText())+"','"+txt_password_register.getText()+"')";

                st=conn.createStatement();
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil");
                this.setVisible(false);
                new ViewLogin().setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Akun Sudah Ada", "Pesan", JOptionPane.WARNING_MESSAGE);
            hapuslayar();
        }
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new ViewLogin().setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UIRegister;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_email_register;
    private javax.swing.JTextField txt_nama_register;
    private javax.swing.JTextField txt_password_register;
    // End of variables declaration//GEN-END:variables
}
